# Generated by Django 6.1 on 2026-09-03 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_rename_answermodel_answer'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionModel',
            new_name='Question',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_title_4188d3_idx',
            old_name='questions_q_title_7ab3b4_idx',
        ),
    ]
